# Immich Live Photo Linker Configuration
# =====================================
# This configuration file contains settings for the Immich Live Photo Linker script.
# - Replace all of the UPPER_CASE variables with your info.

api:
  # You can generate an Immich API key by following the documentation link:
  # https://immich.app/docs/features/command-line-interface#obtain-the-api-key
  api-key: "{YOUR_API_KEY}"
  url: "{http//YOUR_IMMICH_URL:PORT}"
